stages:
  - test
  - build
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug

pre-commit:
  stage: test
  image: musicscience37/pipenv:focal-v3.0
  script:
    - mkdir -p .venv
    - pipenv sync --dev
    - pipenv run pre-commit run --all-files
  needs: []

build:
  stage: build
  image: musicscience37/pipenv:focal-v3.0
  script:
    - mkdir -p .venv
    - pipenv sync
    - pipenv run python3 ./tool.py build -l ja
    - pipenv run python3 ./tool.py build -l en
  artifacts:
    paths:
      - build
    expire_in: "1 week"
  needs: []

pages:
  stage: deploy
  image: ubuntu
  script:
    - mkdir -p public
    - mv build/ja/html public/ja
    - mv build/en/html public/en
    - cp source/KIcon/KIcon.ico public/favicon.ico
    - cp source/KIcon/KIcon128white.png public/KIcon128white.png
  artifacts:
    paths:
      - public
  only:
    - main
  needs: [build]
