stages:
  - test
  - build
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug

pre-commit:
  stage: test
  image: musicscience37/sphinx-doxygen:clang14-v4.3
  script:
    - mkdir -p .venv
    - pipenv sync --dev
    - pipenv run pre-commit run --all-files
  cache:
    key:
      prefix: pipenv-dev
      files:
        - Pipfile.lock
    paths:
      - .venv
  needs: []

build:
  stage: build
  image: musicscience37/sphinx-doxygen:clang14-v4.3
  script:
    - mkdir -p .venv
    - pipenv sync
    - pipenv run python3 ./run.py build -l ja
    - pipenv run python3 ./run.py build -l en
  cache:
    key:
      prefix: pipenv-deploy
      files:
        - Pipfile.lock
    paths:
      - .venv
  artifacts:
    paths:
      - build
    expire_in: "1 week"
  needs: []

pages:
  stage: deploy
  image: ubuntu
  script:
    - mkdir -p public
    - mv build/ja/html public/ja
    - mv build/en/html public/en
  artifacts:
    paths:
      - public
  #only:
  #  - master
  needs: [build]
