[tool.poetry]
name = "musicscience37"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = []
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
sphinx = "^7.2.6"
sphinx-orange-book-theme = "^0.6.0"
sphinxext-opengraph = "^0.9.1"
click = "^8.1.7"
myst-parser = "^2.0.0"
sphinxcontrib-youtube = "^1.4.1"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
doc8 = "^1.1.1"
pre-commit = "^3.6.2"
sphinx-autobuild = "^2024.2.4"
sphinx-intl = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
