[tool.poetry]
name = "musicscience37"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
sphinx = "^7.2.6"
sphinx-rtd-theme = "^1.3.0"
sphinxext-opengraph = "^0.8.2"
click = "^8.1.7"
myst-parser = "^2.0.0"
sphinxcontrib-bibtex = "^2.5.0"
sphinxcontrib-youtube = "^1.4.1"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
doc8 = "^0.11.2"
pre-commit = "^3.4.0"
pylint = "^3.0.1"
sphinx-autobuild = "^2021.3.14"
sphinx-intl = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
