[tool.poetry]
name = "musicscience37"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = []
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
sphinx = "^7.3.7"
sphinx-orange-book-theme = "^0.7.0"
sphinxext-opengraph = "^0.9.1"
click = "^8.1.7"
myst-parser = "^3.0.0"
sphinxcontrib-youtube = "^1.4.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
doc8 = "^1.1.1"
pre-commit = "^3.7.0"
sphinx-autobuild = "^2024.4.16"
sphinx-intl = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
