[tool.poetry]
name = "musicscience37"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = [{ include = "source" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
sphinx = "^6.1.3"
sphinx-rtd-theme = "^1.2.0"
sphinxext-opengraph = "^0.8.1"
click = "^8.1.3"
myst-parser = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
doc8 = "^0.11.2"
pre-commit = "^3.2.0"
pylint = "^2.17.1"
sphinx-autobuild = "^2021.3.14"
sphinx-intl = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
