[tool.poetry]
name = "musicscience37"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = [{ include = "source" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.1.1"
sphinxext-opengraph = "^0.7.3"
click = "^8.1.3"
myst-parser = "^0.18.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
doc8 = "^0.11.2"
pre-commit = "^2.20.0"
pylint = "^2.15.8"
sphinx-autobuild = "^2021.3.14"
sphinx-intl = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
