[tool.poetry]
name = "musicscience37"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
sphinx = "^6.2.1"
sphinx-orange-book-theme = "^0.1.1"
sphinxext-opengraph = "^0.9.1"
click = "^8.1.7"
myst-parser = "^2.0.0"
sphinxcontrib-youtube = "^1.4.1"
sphinx-jinja = "^2.0.2"
pyyaml = "^6.0.1"
types-pyyaml = "^6.0.12.12"

[tool.poetry.group.dev.dependencies]
black = "^23.12.0"
doc8 = "^1.1.1"
pre-commit = "^3.6.0"
pylint = "^3.0.3"
sphinx-autobuild = "^2021.3.14"
sphinx-intl = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
