[tool.poetry]
name = "musicscience37"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
sphinx = "^6.1.3"
sphinx-rtd-theme = "^1.2.2"
sphinxext-opengraph = "^0.8.2"
click = "^8.1.3"
myst-parser = "^2.0.0"
sphinxcontrib-bibtex = "^2.5.0"
sphinxcontrib-youtube = "^1.2.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
doc8 = "^0.11.2"
pre-commit = "^3.3.3"
pylint = "^2.17.4"
sphinx-autobuild = "^2021.3.14"
sphinx-intl = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
